### ISSUE TITLE
File not Exist error

### ISSUE THREAD

**Issue by Mondlii** [xiaochuanle/NECAT#34]
I am testing out NECAT with nanopore long reads. I have more than 260x coverage for a 680MB genome size. I am running  into an issue though whenever I run the tool. Please see below my config file, commands and the error output I get. Thank you.

Config file 

PROJECT=draft_config.txt                                                                                                                                                                        ONT_READ_LIST=/PromethionFlonge.fastq                                                                                                                                                           GENOME_SIZE=680000000                                                                                                                                                                           THREADS=4                                                                                                                                                                                       MIN_READ_LENGTH=3000                                                                                                                                                                            PREP_OUTPUT_COVERAGE=40                                                                                                                                                                         OVLP_FAST_OPTIONS=-n 500 -z 20 -b 2000 -e 0.5 -j 0 -u 1 -a 1000                                                                                                                                 OVLP_SENSITIVE_OPTIONS=-n 500 -z 10 -e 0.5 -j 0 -u 1 -a 1000                                                                                                                                    CNS_FAST_OPTIONS=-a 2000 -x 4 -y 12 -l 1000 -e 0.5 -p 0.8 -u 0                                                                                                                                  CNS_SENSITIVE_OPTIONS=-a 2000 -x 4 -y 12 -l 1000 -e 0.5 -p 0.8 -u 0                                                                                                                             TRIM_OVLP_OPTIONS=-n 100 -z 10 -b 2000 -e 0.5 -j 1 -u 1 -a 400                                                                                                                                  ASM_OVLP_OPTIONS=-n 100 -z 10 -b 2000 -e 0.5 -j 1 -u 0 -a 400                                                                                                                                   NUM_ITER=2                                                                                                                                                                                      CNS_OUTPUT_COVERAGE=30                                                                                                                                                                          CLEANUP=1                                                                                                                                                                                       USE_GRID=false                                                                                                                                                                                  GRID_NODE=0                                                                                                                                                                                     GRID_OPTIONS=                                                                                                                                                                                   SMALL_MEMORY=0                                                                                                                                                                                  FSA_OL_FILTER_OPTIONS=                                                                                                                                                                          FSA_ASSEMBLE_OPTIONS=                                                                                                                                                                           FSA_CTG_BRIDGE_OPTIONS=                                                                                                                                                                         POLISH_CONTIGS=true  

Command inputs: These are run on a server cluster and not a single machine

necat.pl correct /draft_config.txt                                                                                                                                    
necat.pl assemble /draft_config.txt                                                                                                                                   
necat.pl bridge /draft_config.txt

The error that I get is:

"File not Exist: @072cbc1c-23e3-471e-bed2-b637ceeea421 runid=211987b51d11c179799528dfeabcba17112754b9 read=7 ch=21 start_time=2021-03-24T18:31:31Z flow_cell_id=AEQ639 protocol_group_id=flngl_AEQ639 sample_id=flngl_AEQ639"

This error comes up 3x for each necat.pl command in my bash script.

The reads I am using are a concatenation of the flongle and PromethION reads from the sequencing run, I am not sure if this could have an effect. 
 Thank you.

**Comment by xing-he529** [comment]
这个问题您解决了吗？我也遇到了类似的问题 ，求解答，谢谢！

**Comment by Mondlii** [comment]
You create a text file in which you write the path to your sequencing reads and then in the config file where it says "```ONT_READ_LIST`=``." you should put in the path to the text file and not your reads.

for the "``` PROJECT=```" part you just put in the name of your project e.g "```Project= necat_assembly```"

**Comment by xing-he529** [comment]
> You create a text file in which you write the path to your sequencing reads and then in the config file where it says "```ONT_READ_LIST`=``." you should put in the path to the text file and not your reads.
> 
> for the "` PROJECT=`" part you just put in the name of your project e.g "`Project= necat_assembly`"

Thank you for your help. It has worked.

Best wishes,

XH
