### ISSUE TITLE
运行necat.pl报错

### ISSUE THREAD

**Issue by YangJianshun** [xiaochuanle/NECAT#4]
报错信息如下：请问如何解决呢？
syntax error at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 47, near "$cfg{"
Global symbol "%env" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 48.
Global symbol "%env" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 51.
Global symbol "%env" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 52.
syntax error at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 53, near "}"
syntax error at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 80, near "$env{"
Global symbol "$cfg" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 80.
Global symbol "@jobs" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 85.
Global symbol "$prjDir" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 91.
Global symbol "$env" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 97.
Global symbol "$env" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 111.
Global symbol "$cfg" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 111.
Global symbol "$cfg" requires explicit package name at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 117.
syntax error at /home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm line 117, near "$cfg{"
/home/yangjianshun/software/NECAT/Linux-amd64/bin/Plgd/Project.pm has too many errors.

**Comment by xiaochuanle** [comment]
应该是Perl版本过低造成的,更新一下Perl就好了. 参考[这个issue](https://github.com/xiaochuanle/NECAT/issues/2)
