### ISSUE TITLE
Does NECAT have the mapping function of nanopore data?

### ISSUE THREAD

**Issue by wang-xilu** [xiaochuanle/NECAT#6]
Does NECAT have the mapping function of nanopore data? I did not find the feature description.Just like mecat2ref.

**Comment by xiaochuanle** [comment]
We use `oc2rm` to perform reference mapping.
```shell
oc2rm [OPTIONS] reads reference mapping_results.m4
```
`reads` and `reference` can be either `FASTA` or `FASTQ` format. `oc2rm` currently only supports [M4](https://github.com/xiaochuanle/MECAT2) format. 

To perform pairwise mapping on Nanopore reads, please use `oc2mkdb` and `oc2pm` together.
First use `oc2mkdb` to pack raw reads into a folder `packed_data`:
```shell
oc2mkdb packed_data read_list.txt
```
Details of `read_list.txt` can be found in Step 1 of Quick Start in NECAT's [README](https://github.com/xiaochuanle/NECAT). Then perform pairwise mapping on the packed data
```shell
oc2pm [OPTIONS] packed_data mapping_results.m4
```
`oc2pm` currently only supports M4 format. In all cases, the default options (except the `-t` option, which specifies the number of CPU threads) are recommended.
